sudo svn update /data/ask
sudo svn update /data/autos
sudo svn update /data/brains
sudo svn update /data/community
sudo svn update /data/daily
sudo svn update /data/daily_old
sudo svn update /data/django_1
sudo svn update /data/django_96
sudo svn update /data/dtimarketplace
sudo svn update /data/marketplace
sudo svn update /data/media
sudo svn update /data/realestate
sudo svn update /data/rguide
sudo svn update /data/sports
sudo svn update /data/tools
sudo svn update /data/xen
